#!/usr/bin/env python3
"""
Mission Runner - Loads and executes missions from JSON files.

This loads a mission file generated by mission_generator.py and runs it
through the bee environment, applying:
- Custom flower positions, priorities, and time windows
- Custom bee orbital parameters
- Scheduled failure events

Results are saved back to JSON for analysis.

Usage:
    # Run a single mission
    python3 mission_runner.py missions/mission_20260206_001.json

    # Run all missions in a directory
    python3 mission_runner.py missions/ --all

    # Run with visualization
    python3 mission_runner.py missions/mission_001.json --visualize
"""

import argparse
import json
import math
import os
import glob
import numpy as np
import torch
from datetime import datetime
from typing import Optional

from bees_env import BeeForagingEnv
from bee_policy import Actor


def load_mission(filepath: str) -> dict:
    """Load a mission from JSON file."""
    with open(filepath, "r") as f:
        return json.load(f)


def apply_flower_config(env: BeeForagingEnv, flowers_config: list[dict]):
    """Apply custom flower configuration to environment."""
    for f_cfg in flowers_config:
        idx = f_cfg["id"]
        if idx < len(env.flowers):
            flower = env.flowers[idx]
            flower.x = f_cfg["x"]
            flower.y = f_cfg["y"]
            flower.pollen = f_cfg["pollen"]
            flower.priority = f_cfg["priority"]
            flower.window_type = f_cfg["window_type"]
            flower.window_start = f_cfg["window_start"]
            flower.window_end = f_cfg["window_end"]


def apply_bee_config(env: BeeForagingEnv, bees_config: list[dict]):
    """Apply custom bee configuration to environment."""
    for b_cfg in bees_config:
        idx = b_cfg["id"]
        if idx < len(env.bees):
            bee = env.bees[idx]
            # Apply orbital parameters (convert degrees to radians)
            bee.a = b_cfg["semi_major"]
            bee.e = b_cfg["eccentricity"]
            bee.i = math.radians(b_cfg["inclination_deg"])
            bee.omega = math.radians(b_cfg["omega_deg"])
            bee.Omega = math.radians(b_cfg["Omega_deg"])
            bee.nu = math.radians(b_cfg["true_anomaly_deg"])
            # Update position based on new orbital params
            bee.update_position()
            # Apply battery capacity
            env._battery_max[idx] = b_cfg["battery_capacity"]
            env._battery[idx] = b_cfg["battery_capacity"]


def process_failure_event(
    env: BeeForagingEnv,
    failure: dict,
    step: int,
    active_failures: dict,
    verbose: bool = True,
) -> bool:
    """
    Process a failure event.
    
    Returns True if a new failure was triggered.
    """
    if failure["step"] != step:
        return False
    
    bee_id = failure["bee_id"]
    failure_type = failure["type"]
    duration = failure["duration"]
    
    if verbose:
        print(f"\n[FAILURE] Step {step}: Bee {bee_id} - {failure_type}")
        print(f"  Duration: {duration} steps, Recoverable: {failure['recoverable']}")
    
    if failure_type == "battery_drain":
        # Instant battery depletion
        env._battery[bee_id] = 0.0
        env._recharge_until[bee_id] = step + duration
        
        # Log tasks being released
        bee = env.bees[bee_id]
        if bee.assigned_flowers and verbose:
            print(f"  Bee {bee_id} releasing flowers: {bee.assigned_flowers}")
    
    elif failure_type == "communication_loss":
        # Mark bee as unable to communicate
        active_failures[bee_id] = {
            "type": "communication_loss",
            "end_step": step + duration,
        }
    
    elif failure_type == "motor_failure":
        # Mark bee as unable to move
        active_failures[bee_id] = {
            "type": "motor_failure",
            "end_step": step + duration,
            "recoverable": failure["recoverable"],
        }
        if not failure["recoverable"]:
            # Permanent failure - truncate bee
            env.bees[bee_id].truncated = True
    
    return True


def run_mission(
    mission: dict,
    model_path: str = "outputs/best_actor.pt",
    use_policy: bool = True,
    verbose: bool = True,
    visualize: bool = False,
) -> dict:
    """
    Run a mission and return results.
    """
    config = mission["config"]
    
    # Create environment
    env = BeeForagingEnv(
        num_bees=config["num_bees"],
        num_flowers=config["num_flowers"],
        grid_size=config["grid_size"],
        max_steps=config["max_steps"],
        retask_board_size=2,
        low_battery_chance=0.0,  # We control failures manually
        verbose=verbose,
    )
    
    obs = env.reset()
    
    # Apply custom configurations
    apply_flower_config(env, mission["flowers"])
    apply_bee_config(env, mission["bees"])
    
    # Recalculate reachability after position changes
    env._mark_reachable_per_bee()
    
    if verbose:
        print("\n" + "=" * 60)
        print(f"MISSION: {mission['mission_id']}")
        print("=" * 60)
        print(f"Difficulty: {config['difficulty']}")
        print(f"Flowers: {config['num_flowers']} ({mission['stats']['hard_windows']}H/{mission['stats']['soft_windows']}S)")
        print(f"Scheduled failures: {len(mission['failures'])}")
        for f in mission["failures"]:
            print(f"  - Bee {f['bee_id']} at step {f['step']}: {f['type']}")
    
    # Load policy
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    actor = None
    if use_policy:
        try:
            actor = Actor(
                num_bees=config["num_bees"],
                action_dim=3,
                num_flowers=config["num_flowers"],
                retask_board_size=2,
                grid_size=config.get("grid_size", 50),
            ).to(device)
            actor.load_state_dict(torch.load(model_path, map_location=device, weights_only=True))
            actor.eval()
        except Exception as e:
            print(f"[WARNING] Could not load policy: {e}, using random actions")
            actor = None
    
    # Tracking
    active_failures = {}  # bee_id -> failure info
    task_passes = []
    harvests = []
    failure_events = []
    step_data = []
    
    max_steps = config["max_steps"]
    final_step = 0
    
    for step in range(max_steps):
        final_step = step
        
        # Process scheduled failures
        for failure in mission["failures"]:
            if process_failure_event(env, failure, step, active_failures, verbose):
                failure_events.append({
                    "step": step,
                    "bee_id": failure["bee_id"],
                    "type": failure["type"],
                })
        
        # Clear expired failures
        for bee_id in list(active_failures.keys()):
            if active_failures[bee_id]["end_step"] <= step:
                if verbose:
                    print(f"[RECOVERY] Step {step}: Bee {bee_id} recovered from {active_failures[bee_id]['type']}")
                del active_failures[bee_id]
        
        # Get actions
        actions = {}
        if actor is not None:
            for agent in env.agents:
                ob = obs[agent]
                ob_tensor = {
                    'position': torch.tensor(ob['position'], dtype=torch.float32).unsqueeze(0).to(device),
                    'status': torch.tensor(ob['status'], dtype=torch.float32).unsqueeze(0).to(device),
                    'flowers': torch.tensor(ob['flowers'], dtype=torch.float32).unsqueeze(0).to(device),
                    'step_count': torch.tensor(ob['step_count'], dtype=torch.float32).unsqueeze(0).to(device),
                    'consensus': torch.tensor(ob['consensus'], dtype=torch.float32).unsqueeze(0).to(device),
                    'retask_board': torch.tensor(ob['retask_board'], dtype=torch.float32).unsqueeze(0).to(device),
                    'action_availability': torch.tensor(ob['action_availability'], dtype=torch.float32).unsqueeze(0).to(device),
                }
                with torch.no_grad():
                    logits = actor(ob_tensor)
                    action = torch.argmax(torch.softmax(logits, dim=-1), dim=-1).item()
                
                # Override action for failed bees
                bee_id = int(agent.split("_")[1])
                if bee_id in active_failures:
                    if active_failures[bee_id]["type"] == "motor_failure":
                        action = 0  # Force DONOTHING
                
                actions[agent] = action
        else:
            import random
            for agent in env.agents:
                actions[agent] = random.choices([0, 1, 2], weights=[0.2, 0.7, 0.1])[0]
        
        # Track retask boards before step
        boards_before = {i: set(t["flower_id"] for t in env.bees[i].retask_board) for i in range(config["num_bees"])}
        
        # Execute step
        result = env.step(actions)
        obs = result[0]
        
        # Track task passing
        for i in range(config["num_bees"]):
            current = set(t["flower_id"] for t in env.bees[i].retask_board)
            new_tasks = current - boards_before[i]
            for fid in new_tasks:
                task = next((t for t in env.bees[i].retask_board if t["flower_id"] == fid), None)
                if task:
                    task_passes.append({
                        "step": step,
                        "from_bee": task.get("source_bee", -1),
                        "to_bee": i,
                        "flower_id": fid,
                        "hops": task.get("hops", 1),
                    })
        
        # Track harvests
        for i, flower in enumerate(env.flowers):
            if flower.harvested and flower.harvested_step == step:
                harvests.append({
                    "step": step,
                    "flower_id": i,
                    "pollen": flower.pollen,
                    "window_type": mission["flowers"][i]["window_type"],
                })
        
        # Record step data
        step_data.append({
            "step": step,
            "harvested": sum(1 for f in env.flowers if f.harvested),
            "active_bees": sum(1 for i in range(config["num_bees"]) 
                              if not env.bees[i].truncated and env._recharge_until[i] <= step),
        })
        
        # Check termination
        all_harvested = all(f.harvested for f in env.flowers)
        all_done = all(result[2].values()) or all(result[3].values())
        
        if all_harvested or all_done:
            break
    
    # Calculate results
    harvested_count = sum(1 for f in env.flowers if f.harvested)
    total_pollen = sum(f.pollen for f in env.flowers if f.harvested)
    
    # Window success rates
    hard_flowers = [f for f in mission["flowers"] if f["window_type"] == "HARD"]
    soft_flowers = [f for f in mission["flowers"] if f["window_type"] == "SOFT"]
    
    hard_harvested = sum(1 for f in hard_flowers if env.flowers[f["id"]].harvested)
    soft_harvested = sum(1 for f in soft_flowers if env.flowers[f["id"]].harvested)
    
    results = {
        "mission_id": mission["mission_id"],
        "completed_at": datetime.now().isoformat(),
        "success": harvested_count == config["num_flowers"],
        "steps_taken": final_step + 1,
        "flowers_harvested": harvested_count,
        "flowers_total": config["num_flowers"],
        "pollen_collected": round(total_pollen, 2),
        "pollen_total": mission["stats"]["total_pollen"],
        "hard_window_success": f"{hard_harvested}/{len(hard_flowers)}",
        "soft_window_success": f"{soft_harvested}/{len(soft_flowers)}",
        "failures_triggered": len(failure_events),
        "task_passes": len(task_passes),
        "events": {
            "harvests": harvests,
            "failures": failure_events,
            "task_passes": task_passes,
        },
        "step_data": step_data,
    }
    
    if verbose:
        print("\n" + "=" * 60)
        print("MISSION RESULTS")
        print("=" * 60)
        print(f"Success: {'YES' if results['success'] else 'NO'}")
        print(f"Flowers: {harvested_count}/{config['num_flowers']}")
        print(f"Pollen: {total_pollen:.1f}/{mission['stats']['total_pollen']:.1f}")
        print(f"Steps: {final_step + 1}/{max_steps}")
        print(f"HARD windows: {hard_harvested}/{len(hard_flowers)}")
        print(f"SOFT windows: {soft_harvested}/{len(soft_flowers)}")
        print(f"Failures: {len(failure_events)}")
        print(f"Task passes: {len(task_passes)}")
    
    return results


def run_all_missions(
    mission_dir: str,
    model_path: str = "outputs/best_actor.pt",
    use_policy: bool = True,
    verbose: bool = False,
    save_results: bool = True,
) -> list[dict]:
    """Run all missions in a directory."""
    
    pattern = os.path.join(mission_dir, "*.json")
    mission_files = sorted(glob.glob(pattern))
    
    if not mission_files:
        print(f"No mission files found in {mission_dir}")
        return []
    
    print(f"\nFound {len(mission_files)} missions in {mission_dir}")
    
    all_results = []
    
    for i, filepath in enumerate(mission_files):
        # Skip results files
        if "_results" in filepath:
            continue
        
        mission = load_mission(filepath)
        print(f"\n[{i+1}/{len(mission_files)}] Running {mission['mission_id']}...", end=" ")
        
        results = run_mission(
            mission=mission,
            model_path=model_path,
            use_policy=use_policy,
            verbose=verbose,
        )
        
        all_results.append(results)
        
        status = "SUCCESS" if results["success"] else "PARTIAL"
        print(f"{status} ({results['flowers_harvested']}/{results['flowers_total']} flowers)")
        
        # Save individual results
        if save_results:
            results_path = filepath.replace(".json", "_results.json")
            with open(results_path, "w") as f:
                json.dump(results, f, indent=2)
    
    # Summary
    successes = sum(1 for r in all_results if r["success"])
    total_harvested = sum(r["flowers_harvested"] for r in all_results)
    total_flowers = sum(r["flowers_total"] for r in all_results)
    total_passes = sum(r["task_passes"] for r in all_results)
    
    print("\n" + "=" * 60)
    print("BATCH RESULTS")
    print("=" * 60)
    print(f"Missions: {successes}/{len(all_results)} successful")
    print(f"Total flowers: {total_harvested}/{total_flowers} ({100*total_harvested/total_flowers:.1f}%)")
    print(f"Total task passes: {total_passes}")
    
    return all_results


def main():
    parser = argparse.ArgumentParser(description="Run bee swarm missions")
    parser.add_argument("mission", type=str, help="Mission file or directory")
    parser.add_argument("--all", action="store_true", help="Run all missions in directory")
    parser.add_argument("--model", type=str, default="outputs/best_actor.pt", help="Model path")
    parser.add_argument("--no-policy", action="store_true", help="Use random actions")
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose output")
    parser.add_argument("--visualize", action="store_true", help="Show visualization")
    parser.add_argument("--no-save", action="store_true", help="Don't save results")
    
    args = parser.parse_args()
    
    if args.all or os.path.isdir(args.mission):
        mission_dir = args.mission if os.path.isdir(args.mission) else os.path.dirname(args.mission)
        run_all_missions(
            mission_dir=mission_dir,
            model_path=args.model,
            use_policy=not args.no_policy,
            verbose=args.verbose,
            save_results=not args.no_save,
        )
    else:
        mission = load_mission(args.mission)
        results = run_mission(
            mission=mission,
            model_path=args.model,
            use_policy=not args.no_policy,
            verbose=True,
            visualize=args.visualize,
        )
        
        if not args.no_save:
            results_path = args.mission.replace(".json", "_results.json")
            with open(results_path, "w") as f:
                json.dump(results, f, indent=2)
            print(f"\nResults saved to {results_path}")


if __name__ == "__main__":
    main()
